### ISSUE TITLE
Zepto常用API剥离

### ISSUE THREAD

**Issue by spemoon** [spemoon/mobi#4]
### Core

核心方法，最终删除：$.camelCase, pluck, prop, reduce。其他保留
- $()
  - 功能：通过执行css选择器包装dom节点，创建元素或者从一个html片段来创建一个Zepto对象。
  - 备注：
  - 结果：保留
- $.camelCase(string) => string
  - 功能：将一组字符串变成“骆驼”命名法的新字符串，如果该字符已经是“骆驼”命名法，则不变化。
  - 备注：
  - 结果：删除
- $.contains(parent, node) => boolean
  - 功能：检查父节点是否包含给定的dom节点，如果两者相同，则返回 false。
  - 备注：
  - 结果：保留
- $.each(collection, function(index, item){ ... }) => collection
  - 功能：遍历数组元素或以key-value值对方式遍历对象。回调函数返回 false 时停止遍历。
  - 备注：
  - 结果：保留
- $.extend([true], target, [source, ....])   => target
  - 功能：通过源对象扩展目标对象的属性，源对象属性将覆盖目标对象属性。
  - 备注：默认情况下为，复制为浅复制。如果第一个参数为true表示深度复制。
  - 结果：保留
- $.fn
  - 功能：Zepto.fn是一个对象，它拥有Zepto对象上所有可用的方法。如 addClass()， attr()，和其它方法。在这个对象添加一个方法，所有的Zepto对象上都能用到该方法。
  - 备注：
  - 结果：保留
- $.grep(items, function(item){ ... })  =>  array
  - 功能：获取一个新数组，新数组只包含回调函数中返回 ture 的数组项。
  - 备注：
  - 结果：保留
- $.inArray(element, array, [fromIndex])  => number
  - 功能：搜索数组中指定值并返回它的索引（如果没有找到则返回-1）。
  - 备注：[fromIndex] 参数可选，表示从哪个索引值开始向后查找。
  - 结果：保留
- $.isArray(object)  =>  boolean
  - 功能：如果object是array，则返回ture。
  - 备注：
  - 结果：保留
- $.isFunction(object) => boolean
  - 功能：如果object是function，则返回ture。
  - 备注：
  - 结果：保留
- $.isPlainObject(object)  ⇒ boolean
  - 功能：测试对象是否是纯粹的对象（通过 "{}" 或者 "new Object" 创建的），如果是，则返回true。
  - 备注：
  - 结果：保留
- $.isWindow(object) => boolean
  - 功能：确定参数是否为一个窗口（window对象），如果是则返回true。
  - 备注：这在处理iframe时非常有用，因为每个iframe都有它们自己的window对象，使用常规方法obj==window校验这些objects的时候会失败。
  - 结果：保留
- $.map(collection, function(item, index){ ... })  => boolean
  - 功能：通过遍历集合中的元素，通过函数返回一个新的数组，null and undefined 将被过滤掉。
  - 备注：
  - 结果：保留
- $.parseJSON(string)  => object
  - 功能：类似本地JSON.parse 方法，接受一个标准格式的 JSON 字符串，并返回解析后的 JavaScript 对象。
  - 备注：
  - 结果：保留
- $.trim(string)  => string
  - 功能：删除字符串开始和末尾的空白符。类似String.prototype.trim()。
  - 备注：
  - 结果：保留
- $.type(object)  => sring
  - 功能：获取JavaScript 对象的类型。可能的类型有： null undefined boolean number string function array date regexp object error。
  - 备注：
  - 结果：保留
- add(selector, [context])  =>  self
  - 功能：添加元素到匹配的元素集合。如果content参数存在，只在content中进行查找，否则在document中查找。
  - 备注：
  - 结果：保留
- addClass(name) => self
  addClass(function(index, oldClassName){ ... })  => self
  - 功能：为每个匹配的元素添加指定的class类名。多个class类名通过空格分隔。
  - 备注：
  - 结果：保留
- after(content)  ⇒ self
  - 功能：在每个匹配的元素后插入内容。内容可以为html字符串，dom节点，或者节点组成的数组。
  - 备注：
  - 结果：保留
- append(content)  ⇒ self
  - 功能：在每个匹配的元素末尾插入内容。内容可以为html字符串，dom节点，或者节点组成的数组。
  - 备注：
  - 结果：保留
- appendTo(target)  ⇒ self
  - 功能：将匹配的元素插入到目标元素的末尾（里面的后面）。
  - 备注：
  - 结果：保留
- attr(name)  ⇒ string
  attr(name, value)  ⇒ self
  attr(name, function(index, oldValue){ ... })  ⇒ self
  attr({ name: value, name2: value2, ... })  ⇒ self
  - 功能：读取或设置dom的属性。
  - 备注：
  - 结果：保留
- before(content)  ⇒ self
  - 功能：在匹配每个元素的前面（外面）插入内容。内容可以为html字符串，dom节点，或者节点组成的数组。
  - 备注：
  - 结果：保留
- children([selector])  ⇒ collection
  - 功能：获得每个匹配元素集合元素的直接子元素，如果selector存在，只返回符合css选择器的元素。
  - 备注：
  - 结果：保留
- clone()  ⇒ collection
  - 功能：通过深度克隆来复制集合中的所有元素。
  - 备注：
  - 结果：保留
- closest(selector, [context])  ⇒ collection
  closest(collection)  ⇒ collection
  closest(element)  ⇒ collection
  - 功能：从元素本身开始，逐级向上级元素匹配，并返回最先匹配selector的祖先元素。如果context节点参数存在。那么直考虑该节点的后代。
  - 备注：这个方法与 parents(selector)有点相像，但他只返回最先匹配的祖先元素。
  - 结果：保留
- concat(nodes, [node2, ...])  ⇒ self
  - 功能：添加元素到一个Zepto对象集合形成一个新数组。如果参数是一个数组，那么这个数组中的元素将会合并到Zepto对象集合中。
  - 备注：
  - 结果：保留
- contents()  ⇒ collection
  - 功能：获得每个匹配元素集合元素的子元素，包括文字和注释节点。.contents()和.children()方法类似，只不过前者包括文本节点以及jQuery对象中产生的HTML元素。
  - 备注：
  - 结果：保留
- css(property)  ⇒ value
  css(property, value)  ⇒ self
  css({ property: value, property2: value2, ... })  ⇒ self
  - 功能：读取或设置dom元素的css属性。
  - 备注：
  - 结果：保留
- data(name)  ⇒ value
  data(name, value)  ⇒ self
  - 功能：读取或写入dom的 data-\* 属性。
  - 备注：
  - 结果：保留
- each(function(index, item){ ... })  ⇒ self
  - 功能：遍历一个Zepto集合对象，为每一个匹配元素执行一个函数。
  - 备注：
  - 结果：保留
- empty()  ⇒ self
  - 功能：从Zepto对象集合中移除所有的dom子节点。
  - 备注：
  - 结果：保留
- eq(index)  ⇒ collection
  - 功能：从当前Zepto对象集合中获取给定索引号的元素。
  - 备注：
  - 结果：保留
- filter(selector)  ⇒ collection
  filter(function(index){ ... })  ⇒ collection
  - 功能：过滤Zepto集合对象，返回的Zepto集合对象里面的项满足参数中的css选择器。
  - 备注：
  - 结果：保留
- find(selector)  ⇒ collection
  find(collection)  ⇒ collection
  find(element)  ⇒ collection
  - 功能：获得当前Zepto集合对象内查找符合css选择器的每个元素的后代。
  - 备注：
  - 结果：保留
- first()  ⇒ collection
  - 功能：获取当前Zepto对象集合中的第一个元素。
  - 备注：
  - 结果：保留
- forEach(function(item, index, array){ ... }, [context]) 
  - 功能：遍历当前Zepto集合对象的买个元素，有点类似 each，但是遍历函数的参数不一样，当函数返回 false 的时候，遍历不会停止。
  - 备注：
  - 结果：保留
- get()  =>  array
  get(index)  => DOM node
  - 功能：从当前Zepto对象集合中获取所有元素或单个元素。当index参数不存在的时候，以普通数组的方式返回所有的元素。当指定index时，只返回该置的元素。这点与与eq不同，该方法返回的不是Zepto集合对象。
  - 备注：
  - 结果：保留
- has(selector)  ⇒ collection
  has(node)  ⇒ collection
  - 功能：判断当前Zepto对象集合的子元素是否有符合选择器的元素，或者是否包含指定的dom节点，如果有，则返回新的Zepto集合对象，该对象过滤掉不含有选择器匹配元素或者不含有指定dom节点的对象。
  - 备注：
  - 结果：保留
- hasClass(name)  ⇒ boolean
  - 功能：检查Zepto对象集合中是否有元素含有指定的class。
  - 备注：
  - 结果：保留
- height()  ⇒ number
  height(value)  ⇒ self
  height(function(index, oldHeight){ ... })  ⇒ self
  - 功能：获取Zepto对象集合中第一个元素的高度；或者设置Zepto对象集合中所有元素的高度。
  - 备注：
  - 结果：保留
- hide()  ⇒ self
  - 功能：通过设置css的属性display 为 none来将Zepto对象集合中的元素隐藏。
  - 备注：
  - 结果：保留
- html()  ⇒ string
  html(content)  ⇒ self
  html(function(index, oldHtml){ ... })  ⇒ self
  - 功能：通过设置css的属性display 为 none来将Zepto对象集合中的元素隐藏。
  - 备注：
  - 结果：保留
- index([element])  ⇒ number
  - 功能：获取一个元素的位置。
  - 备注：
  - 结果：保留
- indexOf(element, [fromIndex])  ⇒ number
  - 功能：在当前Zepto中获取一个元素的位置。
  - 备注：
  - 结果：保留
- indexOf(element, [fromIndex])  ⇒ number
  - 功能：在当前Zepto中获取一个元素的位置。
  - 备注：
  - 结果：保留
- insertAfter(target)  ⇒ self
  - 功能：插入Zepto对象集合中的元素到指定的每个元素后面的dom中。这个有点像 after，但是使用方式相反。
  - 备注：
  - 结果：保留
- insertBefore(target)  ⇒ self
  - 功能：插入Zepto对象集合中的元素到指定的每个元素前面的dom中。这个有点像 before，但是使用方式相反。
  - 备注：
  - 结果：保留
- is(selector)  ⇒ boolean
  - 功能：判断当前Zepto元素集合中的第一个元素是否符css选择器。对于基础支持jquery的非标准选择器类似： :visible包含在可选的“selector”模块中。
  - 备注：
  - 结果：保留
- last()  ⇒ collection
  - 功能：获取Zepto集合对象中最后一个元素。
  - 备注：
  - 结果：保留
- map(function(index, item){ ... })  ⇒ collection
  - 功能：遍历Zepto对象集合中的所有元素。通过遍历函数返回值形成一个新的集合对象。在遍历函数中this关键之指向当前循环的item（遍历函数中的第二个参数）。遍历中返回 null和undefined，遍历将被打断。
  - 备注：
  - 结果：保留
- next()  ⇒ collection
  next(selector)  ⇒ collection
  - 功能：获取Zepto对象集合中每一个元素的下一个兄弟节点(可以选择性的带上过滤选择器)。
  - 备注：
  - 结果：保留
- not(selector)  ⇒ collection
  not(collection)  ⇒ collection
  not(function(index){ ... })  ⇒ collection
  - 功能：过滤当前Zepto对象集合，获取一个新的Zepto对象集合，它里面的元素不能匹配css选择器。
  - 备注：
  - 结果：保留
- offset()  ⇒ object
  offset(coordinates)  ⇒ self
  offset(function(index, oldOffset){ ... })  ⇒ self
  - 功能：获得当前元素相对于document的位置。
  - 备注：
  - 结果：保留
- offsetParent()  ⇒ collection
  - 功能：找到第一个定位过的祖先元素，在ccs中意味着它的position 值为“relative”, “absolute” or “fixed”
  - 备注：
  - 结果：保留
- parent([selector])  ⇒ collection
  - 功能：获取Zepto对象集合中每个元素的直接父元素。如果css选择器参数给出。过滤出符合条件的元素。
  - 备注：
  - 结果：保留
- parents([selector])  ⇒ collection
  - 功能：获取Zepto对象集合每个元素所有的祖先元素。如果css选择器参数给出，过滤出符合条件的元素。
  - 备注：
  - 结果：保留
- pluck(property)  ⇒ array
  - 功能：获取Zepto对象集合中每一个元素的属性值。返回值为 null或undefined值得过滤掉。
  - 备注：
  - 结果：删除
- position()  ⇒ object
  - 功能：获取Zepto对象集合中第一个元素的位置。
  - 备注：
  - 结果：保留
- prepend(content)  ⇒ self
  - 功能：将参数内容插入到每个匹配元素的前面（元素内部）。
  - 备注：
  - 结果：保留
- prependTo(target)  ⇒ self
  - 功能：将所有元素插入到目标前面（元素内）。
  - 备注：
  - 结果：保留
- prev()  ⇒ collection
  prev(selector)  ⇒ collection
  - 功能：获取Zepto对象集合中每一个元素的前一个兄弟节点，通过选择器来进行过滤。
  - 备注：
  - 结果：保留
- prop(name)  ⇒ value
  prop(name, value)  ⇒ self
  prop(name, function(index, oldValue){ ... })  ⇒ self
  - 功能：读取或设置dom元素的属性值。它在读取属性值的情况下优先于 attr，因为这些属性值会因为用户的交互发生改变，如checked and selected。
  - 备注：
  - 结果：删除
- push(element, [element2, ...])  ⇒ self
  - 功能：添加元素到当前Zepto对象的最后。
  - 备注：
  - 结果：保留
- ready(function($){ ... })  ⇒ self
  - 功能：添加一个事件侦听器，当页面dom加载完毕 “DOMContentLoaded” 事件触发时触发。建议使用 $()来代替这种用法。
  - 备注：
  - 结果：保留
- reduce(function(memo, item, index, array){ ... }, [initial])  ⇒ value
  - 功能：与 Array.reduce有相同的用法，遍历当前Zepto对象集合。memo是函数上次的返回值。迭代进行遍历。
  - 备注：
  - 结果：删除
- remove()  ⇒ self
  - 功能：移出当前Zepto对象中的元素。有效的从dom中移除。
  - 备注：
  - 结果：保留
- removeAttr(name)  ⇒ self
  - 功能：移动当前Zepto对象集合中所有元素的指定属性。
  - 备注：
  - 结果：保留
- removeClass([name])  ⇒ self
  removeClass(function(index, oldClassName){ ... })  ⇒ self
  - 功能：移动当前Zepto对象集合中所有元素的指定class。
  - 备注：
  - 结果：保留
- replaceWith(content)  ⇒ self
  - 功能：用提供的内容替换所有匹配的元素。(包含元素本身)。
  - 备注：
  - 结果：保留
- scrollTop()  ⇒ number
  - 功能：获取页面上的滚动元素或者整个窗口已经滚动的像素值。
  - 备注：
  - 结果：保留
- show()  ⇒ self
  - 功能：恢复Zepto对象集合中每个元素默认的“display”值。
  - 备注：
  - 结果：保留
- siblings([selector])  ⇒ collection
  - 功能：获取Zepto集合对象所有兄弟节点。如果css选择器参数给出。过滤出符合选择器的元素。
  - 备注：
  - 结果：保留
- size()  ⇒ number
  - 功能：获取Zepto对象集合中元素的数量。
  - 备注：
  - 结果：保留
- slice(start, [end])  ⇒ array
  - 功能：array中提取的方法。从start开始，如果end 指出。提取不包含end位置的元素。
  - 备注：
  - 结果：保留
- text()  ⇒ string
  text(content)  ⇒ self
  - 功能：获取或者设置所有Zepto对象的文本内容。
  - 备注：
  - 结果：保留
- toggle([setting])  ⇒ self
  - 功能：显示或隐藏匹配元素。
  - 备注：
  - 结果：保留
- toggleClass(names, [setting])  ⇒ self
  toggleClass(function(index, oldClassNames){ ... }, [setting])  ⇒ self
  - 功能：显示或隐藏匹配元素。
  - 备注：
  - 结果：保留
- unwrap()  ⇒ self
  - 功能：将匹配元素的父级元素删除，保留自身（和兄弟元素，如果存在）在原来的位置。
  - 备注：
  - 结果：保留
- val()  ⇒ string
  val(value)  ⇒ self
  val(function(index, oldValue){ ... })  ⇒ self
  - 功能：获取或设置匹配元素的值。当value参数不存在。
  - 备注：
  - 结果：保留
- width()  ⇒ number
  width(value)  ⇒ self
  width(function(index, oldWidth){ ... })  ⇒ self
  - 功能：获取Zepto对象集合中第一个元素的宽；或者设置Zepto对象集合所有元素的宽。
  - 备注：
  - 结果：保留
- wrap(structure)  ⇒ self
  wrap(function(index){ ... })  ⇒ self
  - 功能：在每个匹配的元素外层包上一个html元素。
  - 备注：
  - 结果：保留
- wrapAll(structure)  ⇒ self
  - 功能：在每个匹配的元素外层包上一个html元素。
  - 备注：
  - 结果：保留
- wrapInner(structure)  ⇒ self
  wrapInner(function(index){ ... })  ⇒ self
  - 功能：在匹配元素里的内容外包一层结构。
  - 备注：
  - 结果：保留

**Comment by spemoon** [comment]
## Detect module

该检测方法可以在不同的环境中微调你的站点或者应用程序，并帮助你识别手机和平板；以及不同的浏览器和操作系统。
保留

**Comment by spemoon** [comment]
## Event

结果：$.proxy待讨论，其他保留
- $.Event(type, [properties])  ⇒ event
  - 功能：创建并初始化一个指定的dom事件。如果properties参数给出，使用它来扩展出新的事件对象。默认情况下，事件被设置为冒泡方式；这个可以通过设置bubbles为false来关闭。
  - 备注：初始化的功能可以使用 trigger来触发。
  - 结果：保留
- $.proxy(fn, context)  ⇒ function
  $.proxy(context, property)  ⇒ function
  - 功能：接受一个函数，然后返回一个新函数，并且这个新函数始终保持了特定的上下文语境，新函数中this指向context参数。另外一种形式，原始的function是context对像的方法。
  - 备注：
  - 结果：待讨论
- bind(type, function(e){ ... })  ⇒ self
  bind({ type: handler, type2: handler2, ... })  ⇒ self
  - 功能：为一个元素绑定一个处理事件。
  - 备注：
  - 结果：保留
- delegate(selector, type, function(e){ ... })  ⇒ self
  delegate(selector, { type: handler, type2: handler2, ... })  ⇒ self
  - 功能：基于一组特定的根元素为所有选择器匹配的元素附加一个处理事件，匹配的元素可能现在或将来才创建。
  - 备注：
  - 结果：保留
- die(type, function(e){ ... })  ⇒ self
  die({ type: handler, type2: handler2, ... })  ⇒ self
  - 功能：删除通过 live 添加的事件。
  - 备注：
  - 结果：保留
- live(type, function(e){ ... })  ⇒ self
  live({ type: handler, type2: handler2, ... })  ⇒ self
  - 功能：类似delegate，添加一个个事件处理器到符合目前选择器的所有元素匹配，匹配的元素可能现在或将来才创建。
  - 备注：
  - 结果：保留
- off(type, [selector], function(e){ ... })  ⇒ self
  off({ type: handler, type2: handler2, ... }, [selector])  ⇒ self
  off(type, [selector])  ⇒ self
  off()  ⇒ self
  - 功能：移除通过 on 注册的事件(用bind或者用on注册的事件)。如果没有参数，将移出当前元素上所有的注册事件。
  - 备注：
  - 结果：保留
- on(type, [selector], function(e){ ... })  ⇒ self
  on({ type: handler, type2: handler2, ... }, [selector])  ⇒ self
  - 功能：添加事件到Zepto对象集合上。
  - 备注：
  - 结果：保留
- one(type, function(e){ ... })  ⇒ self
  one({ type: handler, type2: handler2, ... })  ⇒ self
  - 功能：添加一个处理事件到元素。处理函数在每个元素上最多执行一次。
  - 备注：
  - 结果：保留
- trigger(event, [data]) 
  - 功能：在Zepto对象集合的元素上触发指定的事件。
  - 备注：
  - 结果：保留
- triggerHandler(event, [data])  ⇒ self
  - 功能：像 trigger，它只触发事件，但不冒泡。
  - 备注：
  - 结果：保留
- unbind(type, function(e){ ... })  ⇒ self
  unbind({ type: handler, type2: handler2, ... })  ⇒ self
  - 功能：移除通过 bind 注册的事件。
  - 备注：
  - 结果：保留
- undelegate(selector, type, function(e){ ... })  ⇒ self
  undelegate(selector, { type: handler, type2: handler2, ... })  ⇒ self
  - 功能：移除通过delegate 注册的事件。
  - 备注：
  - 结果：保留

**Comment by spemoon** [comment]
## Ajax

保留

**Comment by spemoon** [comment]
## Touch

保留

**Comment by caolvchong** [comment]
# core

## 主要负责：
- ready事件回调
- DOM：选择器、节点查找和写操作，属性的读写操作，样式读写操作
- 扩展

## 功能分类：

### 选择器：
- $: 
- $.contains 使用概率非常低，find,has一般可以胜任

### 语言辅助：  -> underscore
- $.camelCase 对外不保留的话，考虑下是否内部有使用，估计选择器会有使用
- $.each
- $.extend
- $.grep 使用概率非常低,考虑删除
- $.inArray
- $.isArray/$.isFunction/$.isPlainObject 使用概率非常低,如果保留，纳入underscore/$.isWindow 使用概率非常低
- $.map 使用概率非常低
- $.parseJSON
- $.trim
- $.type 直接用tpyeof/isArray/isFunction来做,考虑删除
- $.fn 保留

### DOM操作

#### 写操作
- add 考虑删除/push 考虑删除/concat 考虑删除/slice 考虑删除
- after/before
- append/appendTo
- prepend/prependTo
- clone
- remove/empty
- html/text/replaceWith
- insertAfter 考虑删除/insertBefore 考虑删除
- unwrap/wrap/wrapAll/wrapInner

#### 查找操作
- children/find/slibings/contents
- first/last
- next/prev
- offsetParent/parent/parents/closest
- each/filter/forEach 考虑删除/map 考虑删除/reduce 删除
- eq/get 考虑删除
- index
- size
- indexOf 上面写重复了，此方法jquery不提供，考虑删除
- is/not/has
- pluck 删除

#### 属性操作
- attr
- data
- removeAttr
- prop 考虑保留
- val

#### 样式操作
- css
- addClass/removeClass/hasClass/toggleClass
- height/width
- show/hide/toggle
- offset/position
- scrollTop

#### 其他
- ready

**Comment by spemoon** [comment]
### 选择器
- $.contains 内部使用，find,has内部实现可以利用到，考虑保留

### 语言辅助
- $.camelCase css会用到，考虑保留
- $.grep 删除
- $.isPlainObject 内部使用(init,extend会调用到)，考虑保留
- $.isWindow height,width方法需要用到这个，考虑保留
- $.map 考虑保留，$.fn, parents, children需要调用
- $.type 删除

# 

可考虑内部使用，不暴露相关接口，不过这几个应该属于基本单元，暴露出去是否更利于扩展？

### DOM操作

#### 写操作
- add 删除
- push 属于单元操作，考虑保留
- concat 同push，考虑保留
- slice 同上，考虑保留
- insertAfter/insertBefore 由于zepto设计得巧，这两个删不删无所谓，对代码的冗余基本上没有影响，考虑保留

#### 查找操作
- forEach 属于单元操作，考虑保留
- map 删除
- reduce 属于单元操作，考虑保留
- get 删除
- indexOf 删除
- pluck 删除

#### 属性操作
- prop保留
